### ISSUE TITLE
Add option for targeting all new courses

### ISSUE THREAD

**Issue by mackensen** [LafColITS/moodle-local_course_template#11]
A suggested feature from https://moodle.org/plugins/local_course_template is to allow targeting all new courses in lieu of a regex for idnumbers. The template course would need a specialized name like Template-All.

**Comment by chadberg** [comment]
+1

We're exploring this as an option, and it would be great if we could say 'If you find a match, use it, otherwise use the default 'Template-All'.  Then we could have a department-specific template, and if the department hasn't developed one yet, apply the standard template.
