### ISSUE TITLE
Add event logging for template copy

### ISSUE THREAD

**Issue by chadberg** [LafColITS/moodle-local_course_template#14]
We're examining the possibility of some post-template-copy processing (such as automatically putting instructor contact info into section-0, or renaming some templated activities with the course name). We'd like to trigger this when a template is copied, but there's no event for us to trigger off of. Triggering off of course creation won't work, and triggering off of things that might work (like module creation) looks like the wrong path as well. How about generating some events as well as watching for them?

**Comment by mackensen** [comment]
That's a great idea and should be easy to implement.
