### ISSUE TITLE
Scheduled cleanup task running every second

### ISSUE THREAD

**Issue by mackensen** [LafColITS/moodle-local_course_template#22]
Reported in the plugins repository:

> I believe there's a bug in the most recent version (3.6.2) of this plugin. We're on 3.8.2. I upgraded and it started running a "\local_course_template\task\cleanup_task" every second, filling up the task queue and maxing out our task runners so no other tasks could complete. I tried turning off the new caching option but the behavior persisted. The plugin would not allow me to downgrade to 3.4.1 so I had to uninstall it.

**Comment by andyzito** [comment]
Fixed in #23
