### ISSUE TITLE
No error thrown when using the  same shortname for an existing course

### ISSUE THREAD

**Issue by ghost** [LafColITS/moodle-local_course_template#24]
I'm using Moodle 3.9.2+ (Build: 20201023). installed course template plugin v3.6.3 (2020081200)

When trying to use one of the templates to create a course, it then redirect me to step 2, to select a category.
After selecting a category and being redirected to step 3 /local/course_templates/index.php?step=3
i'm then supposed to enter course fullname and shortname
- When using an existing shortname and click create it just hangs 

Expected behavior
moodle does the verification to see if the shortname is used in any course, if so it throws an error that another course with the same shortname exists

actual results
When clicking the continue button it  changes to  Creating but then nothing happens

**Comment by mackensen** [comment]
This report seems to be about https://moodle.org/plugins/local_course_templates (note the 's' at the end), which is a different plugin altogether. Are you attempting to use the two of them together?

**Comment by ghost** [comment]
apologies. i'll close this case as it seems irrelevant to this plugin
