### ISSUE TITLE
Apply course start and end dates from template course

### ISSUE THREAD

**Issue by mackensen** [LafColITS/moodle-local_course_template#32]
From the Moodle plugins database:

> We've been using this plugin for a while now and, for the most part, it's working as we want. The one thing it's not doing is setting the start/end dates to match those of the template. I've read in forums that it should be using those dates. Instead, all our courses are given "today's date" as the start and empty end dates. If I could figure out a way to get this to work, it would be very helpful.

By design the plugin doesn't do this, because it was developed for a use case where course start and end dates come over from the SIS. I can see how that would be useful functionality. https://moodle.org/plugins/tool_coursedates is another way to accomplish this.

**Comment by bfriesenvcc** [comment]
Thank you for adding this tracker item. I look forward to a future enhancement.

**Comment by mackensen** [comment]
@bfriesenvcc this turned out to be fairly simple to implement; can you please test the code at https://github.com/LafColITS/moodle-local_course_template/tree/32-dates? You'll need to enable the new setting.

**Comment by bfriesenvcc** [comment]
It worked! You're amazing! I did get the attached error messages during installation, though. 
[course template errors.txt](https://github.com/LafColITS/moodle-local_course_template/files/12402013/course.template.errors.txt)

**Comment by mackensen** [comment]
Yes, that's because I didn't bump the version on the plugin yet, so Moodle didn't know about the new strings. Glad to hear it worked for you! I'll do the formal release of the new version tomorrow.
