### ISSUE TITLE
No information on how to actually use it

### ISSUE THREAD

**Issue by mudrd8mz** [LafColITS/moodle-local_course_template#5]
The page https://moodle.org/plugins/local_course_template does not provide any information on how to actually use the plugin - neither in the description, not via a screenshot.

**Comment by mackensen** [comment]
I've updated the documentation to try and make it clear that you don't really use it--you create a course defined in a particular way, and then the plugin runs in the background.

**Comment by mudrd8mz** [comment]
Sorry I wasn't clear. What I meant is that many users do not actually bother to read the README files included with the package. So the Usage information from it could be copied over to the plugin description page, or at least the link to your README.md here on github (https://github.com/LafColITS/moodle-local_course_template/blob/master/README.md) used as the Documentation link on that page.

**Comment by mackensen** [comment]
Thanks, I understand now. I've updated the description and linked over here as you suggested.
